title: "Part 2: Relevance Training - Getting started"
hero_image: images/banner2.png
description: Session 2 of training for teachers introduces the first part of the resources for Year 8 Relevance intervention through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the Relevance intervention resources
  - title: Introduction to the resources
  - title: Overview
  - title: "Task 1: Technical set-up for trial"
  - title: "Task 2: What is App Lab?"
  - title: Resources documents
