title: "Part 3: Relevance Training - Investigating App Lab"
hero_image: images/banner2.png
description: Part 3 of training for teachers introduces the first part of the resources for Year 8 Relevance intervention through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the Relevance intervention resources
  - title: Introduction to the resources
  - title: Overview
  - title: "Task 1: Technical set-up for trial"
  - title: "Task 2: What is App Lab?"
  - title: Resources documents
  - title: "Task 3: Sharing"
  - title: "Task 4: Post-training webinar"
  - title: "Task 5: Completion survey"
