title: RelevanceTraining-Session2-GBICi4
hero_image: images/banner.png
description: RelevanceTraining-Session2-GBICi4 description
version: 4
listed: false
copyedit: false
last_tested: "2020-10-20"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
