title: "Part 3: Relevance Training - Investigating App Lab"
hero_image: images/banner2.png
description: Part 3 of training for teachers introduces the second part of the resources focusing on App Lab for the Year 8 Relevance intervention through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: "Task 1: Technical set-up for trial"
  - title: "Task 2: What is App Lab?"
  - title: "Task 3: User testing"
  - title: "Task 4: Post-training webinar"
  - title: "Task 5: Completion survey"
